import 'dart:io';
import 'dart:math';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:obfuscateflutter/log.dart';
import 'package:obfuscateflutter/utils/string_ele_visitor.dart';
import 'package:obfuscateflutter/yaml_helper.dart';
import 'package:path/path.dart' as p;

final String defaultStringKeyStoreFile = p.join('lib', 'stren_arg.dart');
final String defaultStringKeyName = 'SEK';
final String defaultStringPrefixName = 'SEP';
final String obfStringFuncName = 'des';

void encryptStrings(String projectPath) {
  final libDir = Directory(p.join(projectPath, 'lib'));
  if (!libDir.existsSync()) {
    Log.log('ERROR: lib directory not found in $projectPath');
    exit(-1);
  }

  final pubName = YamlHelper.getPubSpecName(projectPath);
  if (pubName.isEmpty) {
    Log.log('ERROR: cannot read pubspec name');
    exit(-1);
  }

  // 1. Setup key store file: read existing or generate new
  final keyFile = File(p.join(projectPath, defaultStringKeyStoreFile));

  String sep;
  int sek;

  if (keyFile.existsSync()) {
    sep = _readSep(keyFile);
    sek = int.tryParse(_readSek(keyFile)) ?? 0;

    if (sep.isEmpty || sek <= 0) {
      Log.log('ERROR: $defaultStringKeyStoreFile exists but SEP/SEK could not be read');
      exit(-1);
    }

    final existingContent = keyFile.readAsStringSync();
    if (!existingContent.contains('String $obfStringFuncName(')) {
      Log.log('$defaultStringKeyStoreFile missing des() function, regenerating...');
      _writeKeyStoreFile(keyFile, sep, sek);
    }
  } else {
    sep = _genRandomSep();
    sek = _genRandomSek();
    _writeKeyStoreFile(keyFile, sep, sek);
  }

  Log.log('SEP = $sep, SEK = $sek (store: $defaultStringKeyStoreFile)');

  // 2. Collect all .dart files in lib/
  final keyFilePath = keyFile.path;
  final dartFiles = libDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .where((f) => !f.path.endsWith('.g.dart'))
      .where((f) => !f.path.endsWith('.freezed.dart'))
      .where((f) => f.path != keyFilePath)
      .toList();

  Log.log('Found ${dartFiles.length} .dart files to process');

  final importLine = "import 'package:$pubName/stren_arg.dart';";

  for (final file in dartFiles) {
    _processFile(file, sep, sek, importLine);
  }

  Log.log('String encryption complete.');
}

void _processFile(File file, String sep, int sek, String importLine) {
  final source = file.readAsStringSync();

  // Skip if import already exists — prevents duplicate imports on re-run
  final hasImport = source.contains('stren_arg.dart');

  CompilationUnit unit;
  try {
    unit = parseString(content: source).unit;
  } catch (e) {
    Log.log('  WARN: cannot parse ${file.path}, skipping ($e)');
    return;
  }

  final visitor = StringEncryptVisitor(sep, sek, obfStringFuncName);
  unit.accept(visitor);

  if (visitor.replacements.isEmpty) return;

  // Apply replacements end-to-start to preserve offsets
  String modified = source;
  final sorted = visitor.replacements..sort((a, b) => b.offset.compareTo(a.offset));
  for (final rep in sorted) {
    modified = modified.replaceRange(rep.offset, rep.end, rep.replacement);
  }

  // Add import if not already present
  if (!hasImport) {
    modified = _insertImport(modified, importLine, unit);
  }

  file.writeAsStringSync(modified);
  Log.log('  ${file.path}: encrypted ${visitor.replacements.length} strings');
}

String _insertImport(String source, String importLine, CompilationUnit unit) {
  final directives = unit.directives;
  if (directives.isNotEmpty) {
    final insertPos = directives.last.end;
    return '${source.substring(0, insertPos)}\n$importLine${source.substring(insertPos)}';
  }
  return '$importLine\n$source';
}

String _readSep(File storeFile) {
  final content = storeFile.readAsStringSync();
  // Match single-quoted
  final m1 = RegExp(r"const String SEP\s*=\s*'([^']*)'").firstMatch(content);
  if (m1 != null) return m1.group(1)!;
  // Match double-quoted
  final m2 = RegExp(r'const String SEP\s*=\s*"([^"]*)"').firstMatch(content);
  return m2?.group(1) ?? '';
}

String _readSek(File storeFile) {
  final content = storeFile.readAsStringSync();
  final match = RegExp(r'const int SEK\s*=\s*(\d+)').firstMatch(content);
  return match?.group(1) ?? '';
}

void _writeKeyStoreFile(File file, String sep, int sek) {
  file.writeAsStringSync('''
// Auto-generated by obfuscateflutter -- do not edit manually.
import 'dart:convert';

const String $defaultStringPrefixName = '$sep';
const int $defaultStringKeyName = $sek;

String $obfStringFuncName(String s) {
  if (!s.startsWith($defaultStringPrefixName)) return s;
  try {
    final encoded = s.substring($defaultStringPrefixName.length);
    final shifted = base64.decode(encoded);
    final bytes = shifted.map((b) => (b - $defaultStringKeyName + 256) % 256).toList();
    return utf8.decode(bytes);
  } catch (_) {
    return s;
  }
}
''');
}

String _genRandomSep() {
  const chars = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz';
  final rand = Random();
  return List.generate(3, (_) => chars[rand.nextInt(chars.length)]).join();
}

int _genRandomSek() => Random().nextInt(255) + 1;
